### ISSUE TITLE
Load data in R

### ISSUE THREAD

**Issue by Si-Chong** [Martin-Jung/Habitatmapping#1]
Can the terrestrial habitat map have a sort of format (e.g. shapefile) that can be easily loaded into R? How should I do?
Thank you!

**Comment by Martin-Jung** [comment]
Hi,
You can download the habitat map [here](https://zenodo.org/record/3925749#.X08xoYvRZPY) as raster image either at level 1 or level 2. The files can then be loaded into R using for instance the `'raster'` package. 

```
library(raster)
# Unzip first
habmap <- raster('iucn_habitatclassification_composite_lvl1_ver003.tif')

```

**Comment by Si-Chong** [comment]
Thank you very much for the hint.
I came up with this plot. It seems the values are continuous, but I thought the habitat types are categorical (i.e. 8 categories as in your paper's Fig. 2a). I am unsure what I have done wrong, and appreciate your suggestions.

```
habmap = read_stars("iucn_habitatclassification_composite_lvl1_ver003.tif")
plot(habmap)
```
![1](https://user-images.githubusercontent.com/49397144/92025109-f6b13380-ed56-11ea-8be1-c63cf12513a5.png)

**Comment by Martin-Jung** [comment]
You need to colour the map obviously with a discrete color legend. Or open the raster in a GIS program and colour it there. Here I have supplied style files in the respective folder with the submission.
Please read tutorial how to do spatial analyses and visualizations with R as these questions are not related to the habitat map.
Some open tutorial books here you can find more with Google.
https://geocompr.robinlovelace.net/index.html
https://rspatial.org/raster/index.html
